task sourcesJar(type: Jar) {
    archiveClassifier.set("sources")
    from android.sourceSets.main.java.srcDirs
}

task packagedAar(type: Jar) {
    dependsOn sourcesJar
    archiveBaseName = "ThorCore"
    archiveVersion = android.defaultConfig.versionName
    archiveExtension = "aar"
    destinationDirectory = file("build")
    from zipTree("build/outputs/aar/ThorCore-release.aar")
    from sourcesJar.archiveFile
}

artifacts {
    archives sourcesJar
    archives packagedAar
}

afterEvaluate {
    packagedAar.dependsOn(bundleReleaseAar)
}